<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CantonesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('cantones')->insert([
                ['id'=>367,'nombre'=>'CUENCA','codigo'=>'1','provincia_id'=>343],
                ['id'=>368,'nombre'=>'GIRON','codigo'=>'2','provincia_id'=>343],
                ['id'=>369,'nombre'=>'GUALACEO','codigo'=>'3','provincia_id'=>343],
                ['id'=>370,'nombre'=>'NABON','codigo'=>'4','provincia_id'=>343],
                ['id'=>371,'nombre'=>'PAUTE','codigo'=>'5','provincia_id'=>343],
                ['id'=>372,'nombre'=>'PUCARA','codigo'=>'6','provincia_id'=>343],
                ['id'=>373,'nombre'=>'SAN FERNANDO','codigo'=>'7','provincia_id'=>343],
                ['id'=>374,'nombre'=>'SANTA ISABEL','codigo'=>'8','provincia_id'=>343],
                ['id'=>375,'nombre'=>'SIGSIG','codigo'=>'9','provincia_id'=>343],
                ['id'=>376,'nombre'=>'OÑA','codigo'=>'10','provincia_id'=>343],
                ['id'=>377,'nombre'=>'CHORDELEG','codigo'=>'11','provincia_id'=>343],
                ['id'=>378,'nombre'=>'EL PAN','codigo'=>'12','provincia_id'=>343],
                ['id'=>379,'nombre'=>'SEVILLA DE ORO','codigo'=>'13','provincia_id'=>343],
                ['id'=>380,'nombre'=>'GUACHAPALA','codigo'=>'14','provincia_id'=>343],
                ['id'=>381,'nombre'=>'CAMILO PONCE ENRIQUEZ','codigo'=>'15','provincia_id'=>343],
                ['id'=>382,'nombre'=>'GUARANDA','codigo'=>'1','provincia_id'=>344],
                ['id'=>383,'nombre'=>'CHILLANES','codigo'=>'2','provincia_id'=>344],
                ['id'=>384,'nombre'=>'CHIMBO','codigo'=>'3','provincia_id'=>344],
                ['id'=>385,'nombre'=>'ECHEANDIA','codigo'=>'4','provincia_id'=>344],
                ['id'=>386,'nombre'=>'SAN MIGUEL','codigo'=>'5','provincia_id'=>344],
                ['id'=>387,'nombre'=>'CALUMA','codigo'=>'6','provincia_id'=>344],
                ['id'=>388,'nombre'=>'LAS NAVES','codigo'=>'7','provincia_id'=>344],
                ['id'=>389,'nombre'=>'AZOGUES','codigo'=>'1','provincia_id'=>345],
                ['id'=>390,'nombre'=>'BIBLIAN','codigo'=>'2','provincia_id'=>345],
                ['id'=>391,'nombre'=>'CAÑAR','codigo'=>'3','provincia_id'=>345],
                ['id'=>392,'nombre'=>'LA TRONCAL','codigo'=>'4','provincia_id'=>345],
                ['id'=>393,'nombre'=>'EL TAMBO','codigo'=>'5','provincia_id'=>345],
                ['id'=>394,'nombre'=>'DELEG','codigo'=>'6','provincia_id'=>345],
                ['id'=>395,'nombre'=>'SUSCAL','codigo'=>'7','provincia_id'=>345],
                ['id'=>396,'nombre'=>'TULCAN','codigo'=>'1','provincia_id'=>346],
                ['id'=>397,'nombre'=>'BOLIVAR','codigo'=>'2','provincia_id'=>346],
                ['id'=>398,'nombre'=>'ESPEJO','codigo'=>'3','provincia_id'=>346],
                ['id'=>399,'nombre'=>'MIRA','codigo'=>'4','provincia_id'=>346],
                ['id'=>400,'nombre'=>'MONTUFAR','codigo'=>'5','provincia_id'=>346],
                ['id'=>401,'nombre'=>'SAN PEDRO DE HUACA','codigo'=>'6','provincia_id'=>346],
                ['id'=>402,'nombre'=>'LATACUNGA','codigo'=>'1','provincia_id'=>347],
                ['id'=>403,'nombre'=>'LA MANA','codigo'=>'2','provincia_id'=>347],
                ['id'=>404,'nombre'=>'PANGUA','codigo'=>'3','provincia_id'=>347],
                ['id'=>405,'nombre'=>'PUJILI','codigo'=>'4','provincia_id'=>347],
                ['id'=>406,'nombre'=>'SALCEDO','codigo'=>'5','provincia_id'=>347],
                ['id'=>407,'nombre'=>'SAQUISILI','codigo'=>'6','provincia_id'=>347],
                ['id'=>408,'nombre'=>'SIGCHOS','codigo'=>'7','provincia_id'=>347],
                ['id'=>409,'nombre'=>'RIOBAMBA','codigo'=>'1','provincia_id'=>348],
                ['id'=>410,'nombre'=>'ALAUSI','codigo'=>'2','provincia_id'=>348],
                ['id'=>411,'nombre'=>'COLTA','codigo'=>'3','provincia_id'=>348],
                ['id'=>412,'nombre'=>'CHAMBO','codigo'=>'4','provincia_id'=>348],
                ['id'=>413,'nombre'=>'CHUNCHI','codigo'=>'5','provincia_id'=>348],
                ['id'=>414,'nombre'=>'GUAMOTE','codigo'=>'6','provincia_id'=>348],
                ['id'=>415,'nombre'=>'GUANO','codigo'=>'7','provincia_id'=>348],
                ['id'=>416,'nombre'=>'PALLATANGA','codigo'=>'8','provincia_id'=>348],
                ['id'=>417,'nombre'=>'PENIPE','codigo'=>'9','provincia_id'=>348],
                ['id'=>418,'nombre'=>'CUMANDA','codigo'=>'10','provincia_id'=>348],
                ['id'=>419,'nombre'=>'MACHALA','codigo'=>'1','provincia_id'=>349],
                ['id'=>420,'nombre'=>'ARENILLAS','codigo'=>'2','provincia_id'=>349],
                ['id'=>421,'nombre'=>'ATAHUALPA','codigo'=>'3','provincia_id'=>349],
                ['id'=>422,'nombre'=>'BALSAS','codigo'=>'4','provincia_id'=>349],
                ['id'=>423,'nombre'=>'CHILLA','codigo'=>'5','provincia_id'=>349],
                ['id'=>424,'nombre'=>'EL GUABO','codigo'=>'6','provincia_id'=>349],
                ['id'=>425,'nombre'=>'HUAQUILLAS','codigo'=>'7','provincia_id'=>349],
                ['id'=>426,'nombre'=>'MARCABELI','codigo'=>'8','provincia_id'=>349],
                ['id'=>427,'nombre'=>'PASAJE','codigo'=>'9','provincia_id'=>349],
                ['id'=>428,'nombre'=>'PIÑAS','codigo'=>'10','provincia_id'=>349],
                ['id'=>429,'nombre'=>'PORTOVELO','codigo'=>'11','provincia_id'=>349],
                ['id'=>430,'nombre'=>'SANTA ROSA','codigo'=>'12','provincia_id'=>349],
                ['id'=>431,'nombre'=>'ZARUMA','codigo'=>'13','provincia_id'=>349],
                ['id'=>432,'nombre'=>'LAS LAJAS','codigo'=>'14','provincia_id'=>349],
                ['id'=>433,'nombre'=>'ESMERALDAS','codigo'=>'1','provincia_id'=>350],
                ['id'=>434,'nombre'=>'ELOY ALFARO','codigo'=>'2','provincia_id'=>350],
                ['id'=>435,'nombre'=>'MUISNE','codigo'=>'3','provincia_id'=>350],
                ['id'=>436,'nombre'=>'QUININDE','codigo'=>'4','provincia_id'=>350],
                ['id'=>437,'nombre'=>'SAN LORENZO','codigo'=>'5','provincia_id'=>350],
                ['id'=>438,'nombre'=>'ATACAMES','codigo'=>'6','provincia_id'=>350],
                ['id'=>439,'nombre'=>'RIOVERDE','codigo'=>'7','provincia_id'=>350],
                ['id'=>441,'nombre'=>'GUAYAQUIL','codigo'=>'1','provincia_id'=>351],
                ['id'=>442,'nombre'=>'ALFREDO BAQUERIZO MORENO (JUJAN)','codigo'=>'2','provincia_id'=>351],
                ['id'=>443,'nombre'=>'BALAO','codigo'=>'3','provincia_id'=>351],
                ['id'=>444,'nombre'=>'BALZAR','codigo'=>'4','provincia_id'=>351],
                ['id'=>445,'nombre'=>'COLIMES','codigo'=>'5','provincia_id'=>351],
                ['id'=>446,'nombre'=>'DAULE','codigo'=>'6','provincia_id'=>351],
                ['id'=>447,'nombre'=>'DURAN','codigo'=>'7','provincia_id'=>351],
                ['id'=>448,'nombre'=>'EL EMPALME','codigo'=>'8','provincia_id'=>351],
                ['id'=>449,'nombre'=>'EL TRIUNFO','codigo'=>'9','provincia_id'=>351],
                ['id'=>450,'nombre'=>'MILAGRO','codigo'=>'10','provincia_id'=>351],
                ['id'=>451,'nombre'=>'NARANJAL','codigo'=>'11','provincia_id'=>351],
                ['id'=>452,'nombre'=>'NARANJITO','codigo'=>'12','provincia_id'=>351],
                ['id'=>453,'nombre'=>'PALESTINA','codigo'=>'13','provincia_id'=>351],
                ['id'=>454,'nombre'=>'PEDRO CARBO','codigo'=>'14','provincia_id'=>351],
                ['id'=>455,'nombre'=>'SAMBORONDON','codigo'=>'16','provincia_id'=>351],
                ['id'=>456,'nombre'=>'SANTA LUCIA','codigo'=>'18','provincia_id'=>351],
                ['id'=>457,'nombre'=>'SALITRE (URBINA JADO)','codigo'=>'19','provincia_id'=>351],
                ['id'=>458,'nombre'=>'SAN JACINTO DE YAGUACHI','codigo'=>'20','provincia_id'=>351],
                ['id'=>459,'nombre'=>'PLAYAS','codigo'=>'21','provincia_id'=>351],
                ['id'=>460,'nombre'=>'SIMON BOLIVAR','codigo'=>'22','provincia_id'=>351],
                ['id'=>461,'nombre'=>'CORONEL MARCELINO MARIDUEÑA','codigo'=>'23','provincia_id'=>351],
                ['id'=>462,'nombre'=>'LOMAS DE SARGENTILLO','codigo'=>'24','provincia_id'=>351],
                ['id'=>463,'nombre'=>'NOBOL','codigo'=>'25','provincia_id'=>351],
                ['id'=>464,'nombre'=>'GENERAL ANTONIO ELIZALDE (BUCAY)','codigo'=>'27','provincia_id'=>351],
                ['id'=>465,'nombre'=>'ISIDRO AYORA','codigo'=>'28','provincia_id'=>351],
                ['id'=>466,'nombre'=>'IBARRA','codigo'=>'1','provincia_id'=>352],
                ['id'=>467,'nombre'=>'ANTONIO ANTE','codigo'=>'2','provincia_id'=>352],
                ['id'=>468,'nombre'=>'COTACACHI','codigo'=>'3','provincia_id'=>352],
                ['id'=>469,'nombre'=>'OTAVALO','codigo'=>'4','provincia_id'=>352],
                ['id'=>470,'nombre'=>'PIMAMPIRO','codigo'=>'5','provincia_id'=>352],
                ['id'=>471,'nombre'=>'SAN MIGUEL DE URCUQUI','codigo'=>'6','provincia_id'=>352],
                ['id'=>472,'nombre'=>'LOJA','codigo'=>'1','provincia_id'=>353],
                ['id'=>473,'nombre'=>'CALVAS','codigo'=>'2','provincia_id'=>353],
                ['id'=>474,'nombre'=>'CATAMAYO','codigo'=>'3','provincia_id'=>353],
                ['id'=>475,'nombre'=>'CELICA','codigo'=>'4','provincia_id'=>353],
                ['id'=>476,'nombre'=>'CHAGUARPAMBA','codigo'=>'5','provincia_id'=>353],
                ['id'=>477,'nombre'=>'ESPINDOLA','codigo'=>'6','provincia_id'=>353],
                ['id'=>478,'nombre'=>'GONZANAMA','codigo'=>'7','provincia_id'=>353],
                ['id'=>479,'nombre'=>'MACARA','codigo'=>'8','provincia_id'=>353],
                ['id'=>480,'nombre'=>'PALTAS','codigo'=>'9','provincia_id'=>353],
                ['id'=>481,'nombre'=>'PUYANGO','codigo'=>'10','provincia_id'=>353],
                ['id'=>482,'nombre'=>'SARAGURO','codigo'=>'11','provincia_id'=>353],
                ['id'=>483,'nombre'=>'SOZORANGA','codigo'=>'12','provincia_id'=>353],
                ['id'=>484,'nombre'=>'ZAPOTILLO','codigo'=>'13','provincia_id'=>353],
                ['id'=>485,'nombre'=>'PINDAL','codigo'=>'14','provincia_id'=>353],
                ['id'=>486,'nombre'=>'QUILANGA','codigo'=>'15','provincia_id'=>353],
                ['id'=>487,'nombre'=>'OLMEDO','codigo'=>'16','provincia_id'=>353],
                ['id'=>488,'nombre'=>'BABAHOYO','codigo'=>'1','provincia_id'=>354],
                ['id'=>489,'nombre'=>'BABA','codigo'=>'2','provincia_id'=>354],
                ['id'=>490,'nombre'=>'MONTALVO','codigo'=>'3','provincia_id'=>354],
                ['id'=>491,'nombre'=>'PUEBLOVIEJO','codigo'=>'4','provincia_id'=>354],
                ['id'=>492,'nombre'=>'QUEVEDO','codigo'=>'5','provincia_id'=>354],
                ['id'=>493,'nombre'=>'URDANETA','codigo'=>'6','provincia_id'=>354],
                ['id'=>494,'nombre'=>'VENTANAS','codigo'=>'7','provincia_id'=>354],
                ['id'=>495,'nombre'=>'VINCES','codigo'=>'8','provincia_id'=>354],
                ['id'=>496,'nombre'=>'PALENQUE','codigo'=>'9','provincia_id'=>354],
                ['id'=>497,'nombre'=>'BUENA FE','codigo'=>'10','provincia_id'=>354],
                ['id'=>498,'nombre'=>'VALENCIA','codigo'=>'11','provincia_id'=>354],
                ['id'=>499,'nombre'=>'MOCACHE','codigo'=>'12','provincia_id'=>354],
                ['id'=>500,'nombre'=>'PORTOVIEJO','codigo'=>'1','provincia_id'=>355],
                ['id'=>501,'nombre'=>'BOLIVAR','codigo'=>'2','provincia_id'=>355],
                ['id'=>502,'nombre'=>'CHONE','codigo'=>'3','provincia_id'=>355],
                ['id'=>503,'nombre'=>'EL CARMEN','codigo'=>'4','provincia_id'=>355],
                ['id'=>504,'nombre'=>'FLAVIO ALFARO','codigo'=>'5','provincia_id'=>355],
                ['id'=>505,'nombre'=>'JIPIJAPA','codigo'=>'6','provincia_id'=>355],
                ['id'=>506,'nombre'=>'JUNIN','codigo'=>'7','provincia_id'=>355],
                ['id'=>507,'nombre'=>'MANTA','codigo'=>'8','provincia_id'=>355],
                ['id'=>508,'nombre'=>'MONTECRISTI','codigo'=>'9','provincia_id'=>355],
                ['id'=>509,'nombre'=>'PAJAN','codigo'=>'10','provincia_id'=>355],
                ['id'=>510,'nombre'=>'PICHINCHA','codigo'=>'11','provincia_id'=>355],
                ['id'=>511,'nombre'=>'ROCAFUERTE','codigo'=>'12','provincia_id'=>355],
                ['id'=>512,'nombre'=>'SANTA ANA','codigo'=>'13','provincia_id'=>355],
                ['id'=>513,'nombre'=>'SUCRE','codigo'=>'14','provincia_id'=>355],
                ['id'=>514,'nombre'=>'TOSAGUA','codigo'=>'15','provincia_id'=>355],
                ['id'=>515,'nombre'=>'24 DE MAYO','codigo'=>'16','provincia_id'=>355],
                ['id'=>516,'nombre'=>'PEDERNALES','codigo'=>'17','provincia_id'=>355],
                ['id'=>517,'nombre'=>'OLMEDO','codigo'=>'18','provincia_id'=>355],
                ['id'=>518,'nombre'=>'PUERTO LOPEZ','codigo'=>'19','provincia_id'=>355],
                ['id'=>519,'nombre'=>'JAMA','codigo'=>'20','provincia_id'=>355],
                ['id'=>520,'nombre'=>'JARAMIJO','codigo'=>'21','provincia_id'=>355],
                ['id'=>521,'nombre'=>'SAN VICENTE','codigo'=>'22','provincia_id'=>355],
                ['id'=>522,'nombre'=>'MORONA','codigo'=>'1','provincia_id'=>356],
                ['id'=>523,'nombre'=>'GUALAQUIZA','codigo'=>'2','provincia_id'=>356],
                ['id'=>524,'nombre'=>'LIMON INDANZA','codigo'=>'3','provincia_id'=>356],
                ['id'=>525,'nombre'=>'PALORA','codigo'=>'4','provincia_id'=>356],
                ['id'=>526,'nombre'=>'SANTIAGO','codigo'=>'5','provincia_id'=>356],
                ['id'=>527,'nombre'=>'SUCUA','codigo'=>'6','provincia_id'=>356],
                ['id'=>528,'nombre'=>'HUAMBOYA','codigo'=>'7','provincia_id'=>356],
                ['id'=>529,'nombre'=>'SAN JUAN BOSCO','codigo'=>'8','provincia_id'=>356],
                ['id'=>530,'nombre'=>'TAISHA','codigo'=>'9','provincia_id'=>356],
                ['id'=>531,'nombre'=>'LOGROÑO','codigo'=>'10','provincia_id'=>356],
                ['id'=>532,'nombre'=>'PABLO SEXTO','codigo'=>'11','provincia_id'=>356],
                ['id'=>533,'nombre'=>'TIWINTZA','codigo'=>'12','provincia_id'=>356],
                ['id'=>534,'nombre'=>'TENA','codigo'=>'1','provincia_id'=>357],
                ['id'=>535,'nombre'=>'ARCHIDONA','codigo'=>'3','provincia_id'=>357],
                ['id'=>536,'nombre'=>'EL CHACO','codigo'=>'4','provincia_id'=>357],
                ['id'=>537,'nombre'=>'QUIJOS','codigo'=>'7','provincia_id'=>357],
                ['id'=>538,'nombre'=>'CARLOS JULIO AROSEMENA TOLA','codigo'=>'9','provincia_id'=>357],
                ['id'=>539,'nombre'=>'PASTAZA','codigo'=>'1','provincia_id'=>358],
                ['id'=>540,'nombre'=>'MERA','codigo'=>'2','provincia_id'=>358],
                ['id'=>541,'nombre'=>'SANTA CLARA','codigo'=>'3','provincia_id'=>358],
                ['id'=>542,'nombre'=>'ARAJUNO','codigo'=>'4','provincia_id'=>358],
                ['id'=>543,'nombre'=>'QUITO','codigo'=>'1','provincia_id'=>359],
                ['id'=>544,'nombre'=>'CAYAMBE','codigo'=>'2','provincia_id'=>359],
                ['id'=>545,'nombre'=>'MEJIA','codigo'=>'3','provincia_id'=>359],
                ['id'=>546,'nombre'=>'PEDRO MONCAYO','codigo'=>'4','provincia_id'=>359],
                ['id'=>547,'nombre'=>'RUMIÑAHUI','codigo'=>'5','provincia_id'=>359],
                ['id'=>548,'nombre'=>'SAN MIGUEL DE LOS BANCOS','codigo'=>'7','provincia_id'=>359],
                ['id'=>549,'nombre'=>'PEDRO VICENTE MALDONADO','codigo'=>'8','provincia_id'=>359],
                ['id'=>550,'nombre'=>'PUERTO QUITO','codigo'=>'9','provincia_id'=>359],
                ['id'=>551,'nombre'=>'AMBATO','codigo'=>'1','provincia_id'=>360],
                ['id'=>552,'nombre'=>'BAÑOS DE AGUA SANTA','codigo'=>'2','provincia_id'=>360],
                ['id'=>553,'nombre'=>'CEVALLOS','codigo'=>'3','provincia_id'=>360],
                ['id'=>554,'nombre'=>'MOCHA','codigo'=>'4','provincia_id'=>360],
                ['id'=>555,'nombre'=>'PATATE','codigo'=>'5','provincia_id'=>360],
                ['id'=>556,'nombre'=>'QUERO','codigo'=>'6','provincia_id'=>360],
                ['id'=>557,'nombre'=>'SAN PEDRO DE PELILEO','codigo'=>'7','provincia_id'=>360],
                ['id'=>558,'nombre'=>'SANTIAGO DE PILLARO','codigo'=>'8','provincia_id'=>360],
                ['id'=>559,'nombre'=>'TISALEO','codigo'=>'9','provincia_id'=>360],
                ['id'=>560,'nombre'=>'ZAMORA','codigo'=>'1','provincia_id'=>361],
                ['id'=>561,'nombre'=>'CHINCHIPE','codigo'=>'2','provincia_id'=>361],
                ['id'=>562,'nombre'=>'NANGARITZA','codigo'=>'3','provincia_id'=>361],
                ['id'=>563,'nombre'=>'YACUAMBI','codigo'=>'4','provincia_id'=>361],
                ['id'=>564,'nombre'=>'YANTZAZA','codigo'=>'5','provincia_id'=>361],
                ['id'=>565,'nombre'=>'EL PANGUI','codigo'=>'6','provincia_id'=>361],
                ['id'=>566,'nombre'=>'CENTINELA DEL CONDOR','codigo'=>'7','provincia_id'=>361],
                ['id'=>567,'nombre'=>'PALANDA','codigo'=>'8','provincia_id'=>361],
                ['id'=>568,'nombre'=>'PAQUISHA','codigo'=>'9','provincia_id'=>361],
                ['id'=>569,'nombre'=>'SAN CRISTOBAL','codigo'=>'1','provincia_id'=>362],
                ['id'=>570,'nombre'=>'ISABELA','codigo'=>'2','provincia_id'=>362],
                ['id'=>571,'nombre'=>'SANTA CRUZ','codigo'=>'3','provincia_id'=>362],
                ['id'=>572,'nombre'=>'LAGO AGRIO','codigo'=>'1','provincia_id'=>363],
                ['id'=>573,'nombre'=>'GONZALO PIZARRO','codigo'=>'2','provincia_id'=>363],
                ['id'=>574,'nombre'=>'PUTUMAYO','codigo'=>'3','provincia_id'=>363],
                ['id'=>575,'nombre'=>'SHUSHUFINDI','codigo'=>'4','provincia_id'=>363],
                ['id'=>576,'nombre'=>'SUCUMBIOS','codigo'=>'5','provincia_id'=>363],
                ['id'=>577,'nombre'=>'CASCALES','codigo'=>'6','provincia_id'=>363],
                ['id'=>578,'nombre'=>'CUYABENO','codigo'=>'7','provincia_id'=>363],
                ['id'=>579,'nombre'=>'ORELLANA','codigo'=>'1','provincia_id'=>364],
                ['id'=>580,'nombre'=>'AGUARICO','codigo'=>'2','provincia_id'=>364],
                ['id'=>581,'nombre'=>'LA JOYA DE LOS SACHAS','codigo'=>'3','provincia_id'=>364],
                ['id'=>582,'nombre'=>'LORETO','codigo'=>'4','provincia_id'=>364],
                ['id'=>583,'nombre'=>'SANTO DOMINGO','codigo'=>'1','provincia_id'=>365],
                ['id'=>584,'nombre'=>'SANTA ELENA','codigo'=>'1','provincia_id'=>366],
                ['id'=>585,'nombre'=>'LA LIBERTAD','codigo'=>'2','provincia_id'=>366],
                ['id'=>586,'nombre'=>'SALINAS','codigo'=>'3','provincia_id'=>366],
                ['id'=>440,'nombre'=>'LA CONCORDIA','codigo'=>'8','provincia_id'=>365], // Este quedó fuera en orden pero corresponde a Sto. Domingo
                ['id'=>2775,'nombre'=>'BOLIVAR','codigo'=>'1','provincia_id'=>355], // Extra Manabí
                ['id'=>2821,'nombre'=>'QUINSALOMA','codigo'=>'2','provincia_id'=>354],
        ]);
        //
    }
}
